import { Worker, Customer, ServiceRequest, Booking, LedgerEntry, AdminMetrics } from './types';

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'w1',
    name: 'Suresh Patel',
    phone: '+91 98765 43210',
    avatar: 'https://i.pravatar.cc/150?img=11',
    skills: ['Electrical', 'Wiring', 'Panel Installation'],
    serviceArea: 'Koramangala, HSR Layout, BTM Layout',
    rating: 4.8,
    completedJobs: 142,
    verificationStatus: 'verified',
    isAvailable: true,
    recentJobCount: 8,
    recentEarnings: 12400,
    availableHours: 40,
    joinedDate: '2024-01-15',
  },
  {
    id: 'w2',
    name: 'Rajesh Kumar',
    phone: '+91 87654 32109',
    avatar: 'https://i.pravatar.cc/150?img=12',
    skills: ['Plumbing', 'Pipe Fitting', 'Bathroom Fixtures'],
    serviceArea: 'Indiranagar, Domlur, Ulsoor',
    rating: 4.6,
    completedJobs: 98,
    verificationStatus: 'verified',
    isAvailable: true,
    recentJobCount: 5,
    recentEarnings: 7800,
    availableHours: 35,
    joinedDate: '2024-02-20',
  },
  {
    id: 'w3',
    name: 'Mohan Das',
    phone: '+91 76543 21098',
    avatar: 'https://i.pravatar.cc/150?img=13',
    skills: ['Carpentry', 'Furniture Assembly', 'Door Fitting'],
    serviceArea: 'Whitefield, Marathahalli, Bellandur',
    rating: 4.9,
    completedJobs: 211,
    verificationStatus: 'verified',
    isAvailable: false,
    recentJobCount: 12,
    recentEarnings: 18600,
    availableHours: 45,
    joinedDate: '2023-11-10',
  },
  {
    id: 'w4',
    name: 'Kavitha Rao',
    phone: '+91 65432 10987',
    avatar: 'https://i.pravatar.cc/150?img=5',
    skills: ['Cleaning', 'Deep Clean', 'Post-construction'],
    serviceArea: 'Jayanagar, JP Nagar, Banashankari',
    rating: 4.7,
    completedJobs: 187,
    verificationStatus: 'verified',
    isAvailable: true,
    recentJobCount: 10,
    recentEarnings: 9800,
    availableHours: 48,
    joinedDate: '2023-12-05',
  },
  {
    id: 'w5',
    name: 'Arun Sharma',
    phone: '+91 54321 09876',
    avatar: 'https://i.pravatar.cc/150?img=15',
    skills: ['Appliance Repair', 'AC Service', 'Refrigerator'],
    serviceArea: 'Electronic City, Bannerghatta, Bommanahalli',
    rating: 4.5,
    completedJobs: 76,
    verificationStatus: 'pending',
    isAvailable: true,
    recentJobCount: 3,
    recentEarnings: 4200,
    availableHours: 30,
    joinedDate: '2024-06-01',
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'c1',
    name: 'Priya Mehra',
    phone: '+91 91234 56789',
    avatar: 'https://i.pravatar.cc/150?img=47',
    address: 'Flat 3B, Sunrise Apartments, Koramangala, Bangalore 560034',
    totalBookings: 14,
  },
];

export const MOCK_REQUESTS: ServiceRequest[] = [
  {
    id: 'req1',
    customerId: 'c1',
    customerName: 'Priya Mehra',
    customerAddress: 'Flat 3B, Sunrise Apartments, Koramangala',
    category: 'Electrical',
    subcategory: 'Wiring Issue',
    description: 'Frequent tripping of circuit breaker in kitchen. Needs inspection.',
    urgency: 'normal',
    preferredDate: '2026-09-28',
    preferredTime: '10:00 AM – 12:00 PM',
    estimatedValue: 1200,
    status: 'matching',
    createdAt: '2026-09-27T08:30:00Z',
  },
  {
    id: 'req2',
    customerId: 'c1',
    customerName: 'Priya Mehra',
    customerAddress: 'Flat 3B, Sunrise Apartments, Koramangala',
    category: 'Plumbing',
    subcategory: 'Leaking Pipe',
    description: 'Under-sink pipe leaking in bathroom. Water dripping constantly.',
    urgency: 'urgent',
    preferredDate: '2026-09-27',
    preferredTime: 'ASAP',
    estimatedValue: 800,
    status: 'offered',
    createdAt: '2026-09-27T09:00:00Z',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    requestId: 'req2',
    workerId: 'w2',
    workerName: 'Rajesh Kumar',
    workerAvatar: 'https://i.pravatar.cc/150?img=12',
    workerPhone: '+91 87654 32109',
    workerRating: 4.6,
    customerId: 'c1',
    category: 'Plumbing',
    subcategory: 'Leaking Pipe',
    description: 'Under-sink pipe leaking in bathroom.',
    scheduledDate: '2026-09-27',
    scheduledTime: 'ASAP',
    address: 'Flat 3B, Sunrise Apartments, Koramangala',
    status: 'en_route',
    serviceValue: 800,
    workerShare: 680,
    cooperativePool: 120,
    otp: '4829',
    statusHistory: [
      { status: 'accepted', timestamp: '2026-09-27T09:05:00Z', note: 'Worker accepted' },
      { status: 'en_route', timestamp: '2026-09-27T09:20:00Z', note: 'Worker on the way' },
    ],
  },
  {
    id: 'b2',
    requestId: 'req3',
    workerId: 'w1',
    workerName: 'Suresh Patel',
    workerAvatar: 'https://i.pravatar.cc/150?img=11',
    workerPhone: '+91 98765 43210',
    workerRating: 4.8,
    customerId: 'c1',
    category: 'Electrical',
    subcategory: 'Fan Installation',
    description: 'Install ceiling fan in bedroom.',
    scheduledDate: '2026-09-20',
    scheduledTime: '11:00 AM',
    address: 'Flat 3B, Sunrise Apartments, Koramangala',
    status: 'completed',
    serviceValue: 650,
    workerShare: 552,
    cooperativePool: 98,
    otp: '7341',
    statusHistory: [
      { status: 'accepted', timestamp: '2026-09-19T14:00:00Z', note: 'Worker accepted' },
      { status: 'completed', timestamp: '2026-09-20T12:30:00Z', note: 'Job completed' },
    ],
    rating: 5,
    review: 'Excellent work, very professional!',
  },
];

export const MOCK_JOB_OFFERS = [
  {
    id: 'jo1',
    requestId: 'req4',
    customerId: 'c2',
    category: 'Electrical',
    subcategory: 'Circuit Breaker',
    description: 'Frequent tripping in kitchen area. Needs inspection and possible rewiring.',
    customerArea: 'Koramangala (2.3 km away)',
    scheduledDate: '2026-09-28',
    scheduledTime: '10:00 AM – 12:00 PM',
    serviceValue: 1200,
    workerShare: 1020,
    allocationReason: 'Matched to your Electrical skill · Nearby · Your recent workload is lower than other eligible workers',
    expiresInSeconds: 180,
    distance: '2.3 km',
    estimatedTravel: '12 min',
  },
  {
    id: 'jo2',
    requestId: 'req5',
    customerId: 'c3',
    category: 'Electrical',
    subcategory: 'Light Fixture',
    description: 'Replace 4 tube lights with LED panels in living room.',
    customerArea: 'HSR Layout (1.8 km away)',
    scheduledDate: '2026-09-29',
    scheduledTime: '2:00 PM – 4:00 PM',
    serviceValue: 900,
    workerShare: 765,
    allocationReason: 'Matched to your Electrical skill · Nearby · Available at this time',
    expiresInSeconds: 600,
    distance: '1.8 km',
    estimatedTravel: '9 min',
  },
];

export const MOCK_LEDGER: LedgerEntry[] = [
  {
    id: 'le1',
    bookingId: 'b2',
    date: '2026-09-20',
    category: 'Electrical',
    subcategory: 'Fan Installation',
    serviceValue: 650,
    workerShare: 552,
    cooperativeContribution: 98,
    status: 'paid',
    payoutDate: '2026-09-22',
  },
  {
    id: 'le2',
    bookingId: 'b3',
    date: '2026-09-15',
    category: 'Electrical',
    subcategory: 'Wiring Inspection',
    serviceValue: 1100,
    workerShare: 935,
    cooperativeContribution: 165,
    status: 'paid',
    payoutDate: '2026-09-17',
  },
  {
    id: 'le3',
    bookingId: 'b4',
    date: '2026-09-10',
    category: 'Electrical',
    subcategory: 'Panel Upgrade',
    serviceValue: 2400,
    workerShare: 2040,
    cooperativeContribution: 360,
    status: 'paid',
    payoutDate: '2026-09-12',
  },
  {
    id: 'le4',
    bookingId: 'b5',
    date: '2026-09-05',
    category: 'Electrical',
    subcategory: 'Socket Replacement',
    serviceValue: 450,
    workerShare: 382,
    cooperativeContribution: 68,
    status: 'paid',
    payoutDate: '2026-09-07',
  },
];

export const MOCK_ADMIN_METRICS: AdminMetrics = {
  totalActiveJobs: 24,
  pendingVerifications: 7,
  totalWorkers: 148,
  activeWorkers: 91,
  weeklyGMV: 284600,
  weeklyJobsCompleted: 312,
  disputesPending: 3,
  topConcentration: 28,
  workerOfferRate: 87,
  avgJobsPerWorker: 3.2,
};

export const SERVICE_CATEGORIES = [
  { id: 'electrical', label: 'Electrical', icon: 'flash', color: '#F59E0B', description: 'Wiring, fitting, repairs' },
  { id: 'plumbing', label: 'Plumbing', icon: 'water', color: '#3B82F6', description: 'Pipes, fixtures, leaks' },
  { id: 'carpentry', label: 'Carpentry', icon: 'hammer', color: '#92400E', description: 'Furniture, doors, woodwork' },
  { id: 'cleaning', label: 'Cleaning', icon: 'sparkles', color: '#10B981', description: 'Home, deep, post-construction' },
  { id: 'appliance', label: 'Appliance', icon: 'settings', color: '#8B5CF6', description: 'AC, fridge, washing machine' },
  { id: 'painting', label: 'Painting', icon: 'color-palette', color: '#EC4899', description: 'Interior, exterior, touch-up' },
];
